version: '3.4'
services:
        app:
                build:
                        context: .
                ports:
                        - "${DOCKER_FORWARD_PORT}:5000"
                restart: always
                env_file:
                        - .env
                volumes:
                        - "../docker_volume_logs/${APP_NAME}:/app/logs"