version: '3.4'
services:
        app:
                build:
                        context: .
                ports:
                        - "${DOCKER_FORWARD_PORT}:5000"
                restart: always
                env_file:
                        - .env
                volumes:
                        - "../../docker_volumes/${APP_NAME}/logs:/app/logs"